-- ai_battle_data.lua

------##########-------
---DEBUG BOOL ON OFF---
------##########-------

GLOBAL_DEBUG = true

-----#########---------
---AI UPDATE LIMITER --
-----------------------

BOOL_AIBUL_ENABLED = true  -- AI Battle Update Limiter enabled on or off
MAX_UNITS_PER_FRAME = 1  -- Default hard cap of 1 units/frame
MAX_UNITS_PER_FRAME_HIGH_SETTINGS = 2  -- High settings cap of 2 units/frame

-- Mapping of unit roles to allowed tactic keys
unit_type_tactics = {
    elephant = {391, 401, 403, 405, 411, 412, 417},  -- Added cavalry_recharge (417)
    shock_cavalry = {392, 393, 394, 401, 403, 405, 411, 412, 417, 418},  -- Added cavalry_recharge (417), siege_flank (418)
    melee_cavalry = {392, 393, 394, 401, 403, 405, 411, 412, 417, 418},  -- Added cavalry_recharge (417), siege_flank (418)
    missile_cavalry = {394, 395, 401, 403, 405, 411, 412, 413, 414, 417, 418},  -- Added cavalry_recharge (417), siege_flank (418)
    light_cavalry = {394, 395, 401, 403, 405, 411, 412, 414, 417, 418, 434},  -- Added cavalry_recharge (417), siege_flank (418), forest_ambush (434)
    pike_infantry = {396, 401, 403, 405, 411},  -- Added forest_ambush (434) where applicable
    infantry = {401, 403, 405, 407, 411, 418, 434},  -- Added siege_flank (418), forest_ambush (434)
    ranged = {402, 403, 405, 407, 411, 418},  -- Added siege_flank (418)
    support = {401, 403, 405, 411, 402, 418},  -- Added siege_flank (418)
    chariot = {409, 394, 401, 402, 403, 405, 416, 417, 418}  -- Added cavalry_recharge (417), siege_flank (418)
}


-- Table of all Total War: Rome II factions with their index keys, subcultures, and mapped cultures
local factions = {
    -- 4 main cultures usable by ai cultures battle data. : - rom_hellenistic, rom_roman, rom_eastern, rom_barbarian, default
    
    ["default_nil"] = {index_key = 0000000000, subculture = "default_subculture_nil", culture = "default"},
    ["3c_alani"] = { index_key = 2041770406, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["3c_alani_civil_war"] = { index_key = 2041770990, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["3c_alani_secession"] = { index_key = 2041771044, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["3c_alemanni"] = { index_key = 2041770671, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["3c_ardhan"] = { index_key = 2041770518, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["3c_armenia"] = { index_key = 2041770362, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["3c_armenia_civil_war"] = { index_key = 2041770994, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["3c_armenia_secession"] = { index_key = 2041771046, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["3c_axum"] = { index_key = 2041770501, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["3c_baktria"] = { index_key = 2041770534, subculture = "sc_rom_eastern", culture = "rom_hellenistic" },
    ["3c_blemmyes"] = { index_key = 2041770486, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["3c_bosporou"] = { index_key = 2041770610, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["3c_britannia"] = { index_key = 2041770433, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["3c_burgundii"] = { index_key = 2041770656, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["3c_buri"] = { index_key = 2041770630, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["3c_caledoni"] = { index_key = 2041770375, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["3c_caledoni_civil_war"] = { index_key = 2041770998, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["3c_caledoni_secession"] = { index_key = 2041771055, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["3c_colchis"] = { index_key = 2041770509, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["3c_dahae"] = { index_key = 2041770618, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["3c_ebdani"] = { index_key = 2041770440, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["3c_egypt"] = { index_key = 2041770482, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["3c_franci"] = { index_key = 2041770682, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["3c_galatia"] = { index_key = 2041770507, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["3c_gallicemp"] = { index_key = 2041770424, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["3c_gallicemp_civil_war"] = { index_key = 2041770980, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["3c_gallicemp_secession"] = { index_key = 2041771057, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["3c_garamantia"] = { index_key = 2041770477, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["3c_gerrhea"] = { index_key = 2041770569, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["3c_gothi"] = { index_key = 2041770399, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["3c_gothi_civil_war"] = { index_key = 2041771006, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["3c_gothi_secession"] = { index_key = 2041771060, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["3c_heruli"] = { index_key = 2041770609, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["3c_himyar"] = { index_key = 2041770577, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["3c_hispania"] = { index_key = 2041770452, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["3c_iastae"] = { index_key = 2041770611, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["3c_kartli"] = { index_key = 2041770510, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["3c_kwarezm"] = { index_key = 2041770620, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["3c_lakhmids"] = { index_key = 2041770542, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["3c_langobardi"] = { index_key = 2041770678, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["3c_lusitania"] = { index_key = 2041770446, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["3c_lydia"] = { index_key = 2041770504, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["3c_ma_in"] = { index_key = 2041770560, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["3c_marcomanni"] = { index_key = 2041770393, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["3c_marcomanni_civil_war"] = { index_key = 2041771014, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["3c_marcomanni_secession"] = { index_key = 2041771062, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["3c_margiana"] = { index_key = 2041770531, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["3c_mascat"] = { index_key = 2041770596, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["3c_mauretania"] = { index_key = 2041770463, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["3c_mauri"] = { index_key = 2041770462, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["3c_media"] = { index_key = 2041770522, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["3c_meroe"] = { index_key = 2041770493, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["3c_nabatea"] = { index_key = 2041770551, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["3c_nahanarvali"] = { index_key = 2041770648, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["3c_nasamones"] = { index_key = 2041770478, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["3c_numidia"] = { index_key = 2041770472, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["3c_palmyra"] = { index_key = 2041770374, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["3c_palmyra_civil_war"] = { index_key = 2041771022, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["3c_palmyra_secession"] = { index_key = 2041771068, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["3c_quadi"] = { index_key = 2041770633, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["3c_rebel_african"] = { index_key = 2041771083, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["3c_rebel_arabian"] = { index_key = 2041771088, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["3c_rebel_celtic"] = { index_key = 2041771098, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["3c_rebel_eastern"] = { index_key = 2041771120, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["3c_rebel_germanic"] = { index_key = 2041771106, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["3c_rebel_latin"] = { index_key = 2041771113, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["3c_rebel_nomadic"] = { index_key = 2041771116, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["3c_roman_pretender"] = { index_key = 2041770683, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["3c_roman_secession"] = { index_key = 2041771072, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["3c_rome"] = { index_key = 2041770370, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["3c_roxolani"] = { index_key = 2041770599, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["3c_rugii"] = { index_key = 2041770650, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["3c_saba"] = { index_key = 2041770587, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["3c_sakastan"] = { index_key = 2041770540, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["3c_sassanid"] = { index_key = 2041770415, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["3c_sassanid_civil_war"] = { index_key = 2041771030, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["3c_sassanid_secession"] = { index_key = 2041771075, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["3c_saxoni"] = { index_key = 2041770383, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["3c_saxoni_civil_war"] = { index_key = 2041771038, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["3c_saxoni_secession"] = { index_key = 2041771078, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["3c_semnones"] = { index_key = 2041770659, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["3c_vandali"] = { index_key = 2041770642, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["3c_varini"] = { index_key = 2041770664, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["emp_alani"] = { index_key = 2041769860, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["emp_antony"] = { index_key = 2041769662, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["emp_antony_civil_war"] = { index_key = 2041770121, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["emp_antony_secession"] = { index_key = 2041770685, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["emp_aorsoi"] = { index_key = 2041769852, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["emp_ardhan"] = { index_key = 2041769882, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["emp_arii"] = { index_key = 2041769756, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["emp_armenia"] = { index_key = 2041769704, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["emp_armenia_civil_war"] = { index_key = 2041770148, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["emp_armenia_secession"] = { index_key = 2041770690, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["emp_axum"] = { index_key = 2041769977, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["emp_bastarnae"] = { index_key = 2041769824, subculture = "sc_rom_daco_thracian", culture = "default" },
    ["emp_belgae"] = { index_key = 2041770170, subculture = "sc_rom_celtic", culture = "default" },
    ["emp_blemmyes"] = { index_key = 2041769966, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["emp_boii"] = { index_key = 2041769806, subculture = "sc_rom_celtic", culture = "default" },
    ["emp_breuci"] = { index_key = 2041769810, subculture = "sc_rom_celtic", culture = "default" },
    ["emp_brigantes"] = { index_key = 2041769713, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["emp_buri"] = { index_key = 2041769785, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["emp_caledones"] = { index_key = 2041769722, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["emp_cantabri"] = { index_key = 2041769706, subculture = "sc_rom_celtiberian", culture = "default" },
    ["emp_cappadocia"] = { index_key = 2041769874, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["emp_characene"] = { index_key = 2041769890, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["emp_cherusci"] = { index_key = 2041769731, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["emp_cimbri"] = { index_key = 2041769730, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["emp_corieltauvi"] = { index_key = 2041769710, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["emp_dacia"] = { index_key = 2041769684, subculture = "sc_rom_daco_thracian", culture = "default" },
    ["emp_dacia_civil_war"] = { index_key = 2041770131, subculture = "sc_rom_daco_thracian", culture = "default" },
    ["emp_dacia_secession"] = { index_key = 2041770696, subculture = "sc_rom_daco_thracian", culture = "default" },
    ["emp_dahae"] = { index_key = 2041769856, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["emp_demetae"] = { index_key = 2041769711, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["emp_drangiana"] = { index_key = 2041770180, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["emp_dumonii"] = { index_key = 2041769707, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["emp_ebdani"] = { index_key = 2041769724, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["emp_egypt"] = { index_key = 2041769698, subculture = "sc_rom_egyptian", culture = "default" },
    ["emp_egypt_civil_war"] = { index_key = 2041770145, subculture = "sc_rom_egyptian", culture = "default" },
    ["emp_egypt_secession"] = { index_key = 2041770701, subculture = "sc_rom_egyptian", culture = "default" },
    ["emp_frisii"] = { index_key = 2041769725, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["emp_gaetuli"] = { index_key = 2041769997, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["emp_galatia"] = { index_key = 2041769816, subculture = "sc_rom_celtic", culture = "default" },
    ["emp_garamantia"] = { index_key = 2041769958, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["emp_gaul"] = { index_key = 2041770160, subculture = "sc_rom_celtic", culture = "default" },
    ["emp_gerrhea"] = { index_key = 2041769921, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["emp_gutones"] = { index_key = 2041769749, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["emp_helisii"] = { index_key = 2041769768, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["emp_helveconae"] = { index_key = 2041769766, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["emp_helvetii"] = { index_key = 2041769789, subculture = "sc_rom_celtic", culture = "default" },
    ["emp_himyar"] = { index_key = 2041769947, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["emp_iastae"] = { index_key = 2041769865, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["emp_iberia"] = { index_key = 2041770153, subculture = "sc_rom_celtiberian", culture = "default" },
    ["emp_iceni"] = { index_key = 2041769692, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["emp_iceni_civil_war"] = { index_key = 2041770135, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["emp_iceni_secession"] = { index_key = 2041770710, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["emp_judea"] = { index_key = 2041769899, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["emp_kartli"] = { index_key = 2041769878, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["emp_lazyges"] = { index_key = 2041769836, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["emp_lepidus"] = { index_key = 2041769669, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["emp_lepidus_civil_war"] = { index_key = 2041770126, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["emp_lepidus_secession"] = { index_key = 2041770716, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["emp_ma_in"] = { index_key = 2041769928, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["emp_marcomanni"] = { index_key = 2041769693, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["emp_marcomanni_civil_war"] = { index_key = 2041770140, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["emp_marcomanni_secession"] = { index_key = 2041770723, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["emp_mascat"] = { index_key = 2041769936, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["emp_mauri"] = { index_key = 2041769992, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["emp_media_atropatene"] = { index_key = 2041769883, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["emp_meroe"] = { index_key = 2041769969, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["emp_nabatea"] = { index_key = 2041769909, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["emp_nahanarvali"] = { index_key = 2041769778, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["emp_nasamones"] = { index_key = 2041769951, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["emp_nori"] = { index_key = 2041769799, subculture = "sc_rom_celtic", culture = "default" },
    ["emp_numidia"] = { index_key = 2041769987, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["emp_octavian"] = { index_key = 2041769652, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["emp_octavian_civil_war"] = { index_key = 2041770117, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["emp_octavian_secession"] = { index_key = 2041770733, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["emp_palmyra"] = { index_key = 2041769888, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["emp_paradene"] = { index_key = 2041770188, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["emp_parthia"] = { index_key = 2041769681, subculture = "sc_rom_parthian", culture = "rom_eastern" },
    ["emp_parthia_civil_war"] = { index_key = 2041770130, subculture = "sc_rom_parthian", culture = "rom_eastern" },
    ["emp_parthia_secession"] = { index_key = 2041770737, subculture = "sc_rom_parthian", culture = "rom_eastern" },
    ["emp_persia"] = { index_key = 2041769897, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["emp_pompey"] = { index_key = 2041769678, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["emp_pompey_civil_war"] = { index_key = 2041770127, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["emp_pompey_secession"] = { index_key = 2041770739, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["emp_pontus"] = { index_key = 2041769876, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["emp_qidri"] = { index_key = 2041769917, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["emp_quadi"] = { index_key = 2041769735, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["emp_raeti"] = { index_key = 2041769798, subculture = "sc_rom_celtic", culture = "default" },
    ["emp_rebel_african"] = { index_key = 2041770016, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["emp_rebel_arabian"] = { index_key = 2041770024, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["emp_rebel_briton"] = { index_key = 2041770026, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["emp_rebel_celt"] = { index_key = 2041770033, subculture = "sc_rom_celtic", culture = "default" },
    ["emp_rebel_dacian"] = { index_key = 2041770039, subculture = "sc_rom_celtic", culture = "default" },
    ["emp_rebel_eastern"] = { index_key = 2041770047, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["emp_rebel_egyptian"] = { index_key = 2041770050, subculture = "sc_rom_egyptian", culture = "default" },
    ["emp_rebel_german"] = { index_key = 2041770055, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["emp_rebel_hellenic"] = { index_key = 2041770064, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["emp_rebel_iberian"] = { index_key = 2041770069, subculture = "sc_rom_celtiberian", culture = "default" },
    ["emp_rebel_illyrian"] = { index_key = 2041770079, subculture = "sc_rom_celtic", culture = "default" },
    ["emp_rebel_latin"] = { index_key = 2041770086, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["emp_rebel_nomadic"] = { index_key = 2041770090, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["emp_rebel_punic"] = { index_key = 2041770099, subculture = "sc_rom_carthaginian", culture = "default" },
    ["emp_rebel_spartan"] = { index_key = 2041770109, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["emp_rebel_thracian"] = { index_key = 2041770115, subculture = "sc_rom_celtic", culture = "default" },
    ["emp_roxolani"] = { index_key = 2041769840, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["emp_rugii"] = { index_key = 2041769741, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["emp_saba"] = { index_key = 2041769941, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["emp_scordisci"] = { index_key = 2041769814, subculture = "sc_rom_celtic", culture = "default" },
    ["emp_semnones"] = { index_key = 2041769739, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["emp_siraces"] = { index_key = 2041769845, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["emp_thrace"] = { index_key = 2041769826, subculture = "sc_rom_daco_thracian", culture = "default" },
    ["emp_vindelici"] = { index_key = 2041769809, subculture = "sc_rom_celtic", culture = "default" },
    ["gaul_aedui"] = { index_key = 2041769076, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_allobroges"] = { index_key = 2041769211, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_arverni"] = { index_key = 2041769041, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_arverni_civil_war"] = { index_key = 2041769336, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_arverni_secession"] = { index_key = 2041770747, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_atrebates"] = { index_key = 2041769051, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_ausci"] = { index_key = 2041769129, subculture = "sc_rom_celtic", culture = "default" },
    ["gaul_belgae"] = { index_key = 2041769177, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_bellovaci"] = { index_key = 2041769181, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_bituriges"] = { index_key = 2041769221, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_cadurci"] = { index_key = 2041769230, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_cantiaci"] = { index_key = 2041769206, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["gaul_carnutes"] = { index_key = 2041769079, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_cenomani"] = { index_key = 2041769238, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_dumnonii"] = { index_key = 2041769070, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["gaul_eburones"] = { index_key = 2041769282, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_helvetii"] = { index_key = 2041769083, subculture = "sc_rom_celtic", culture = "default" },
    ["gaul_lemovices"] = { index_key = 2041769244, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_lexovii"] = { index_key = 2041769322, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_mandubii"] = { index_key = 2041769250, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_massilia"] = { index_key = 2041769116, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["gaul_mediomatrici"] = { index_key = 2041769187, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_morini"] = { index_key = 2041769192, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_namnetes"] = { index_key = 2041769042, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_nemetes"] = { index_key = 2041769289, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["gaul_nervii"] = { index_key = 2041769056, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_nervii_civil_war"] = { index_key = 2041769354, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_nervii_secession"] = { index_key = 2041770748, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_osismii"] = { index_key = 2041769146, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_parisii"] = { index_key = 2041769193, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_pictones"] = { index_key = 2041769091, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_raurici"] = { index_key = 2041769295, subculture = "sc_rom_celtic", culture = "default" },
    ["gaul_rebel_briton"] = { index_key = 2041769305, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["gaul_rebel_celt"] = { index_key = 2041769308, subculture = "sc_rom_celtic", culture = "default" },
    ["gaul_rebel_gaul"] = { index_key = 2041769312, subculture = "sc_rom_celtic", culture = "default" },
    ["gaul_rebel_german"] = { index_key = 2041769296, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["gaul_rebel_latin"] = { index_key = 2041769303, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["gaul_redones"] = { index_key = 2041769156, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_remi"] = { index_key = 2041769197, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_rome"] = { index_key = 2041769038, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["gaul_rome_civil_war"] = { index_key = 2041769349, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["gaul_rome_secession"] = { index_key = 2041770758, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["gaul_ruteni"] = { index_key = 2041769256, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_santones"] = { index_key = 2041769257, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_senones"] = { index_key = 2041769126, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_sequani"] = { index_key = 2041769093, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_sotiates"] = { index_key = 2041769134, subculture = "sc_rom_celtic", culture = "default" },
    ["gaul_suebi"] = { index_key = 2041769106, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["gaul_suebi_civil_war"] = { index_key = 2041769344, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["gaul_suebi_secession"] = { index_key = 2041770767, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["gaul_suessiones"] = { index_key = 2041769205, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_tarbelli"] = { index_key = 2041769144, subculture = "sc_rom_celtic", culture = "default" },
    ["gaul_treverii"] = { index_key = 2041769060, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_tulingi"] = { index_key = 2041769269, subculture = "sc_rom_celtic", culture = "default" },
    ["gaul_turones"] = { index_key = 2041769271, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_unelli"] = { index_key = 2041769165, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_vangiones"] = { index_key = 2041769294, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["gaul_veneti"] = { index_key = 2041769168, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_vivisci"] = { index_key = 2041769102, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_vocontii"] = { index_key = 2041769280, subculture = "sc_rom_gaul", culture = "default" },
    ["gaul_volcae"] = { index_key = 2041769104, subculture = "sc_rom_gaul", culture = "default" },
    ["inv_aequi"] = { index_key = 2041771302, subculture = "sc_rom_italic", culture = "default" },
    ["inv_agrigento"] = { index_key = 2041771387, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["inv_agyrion"] = { index_key = 2041771379, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["inv_aleria"] = { index_key = 2041771403, subculture = "sc_rom_etruscan", culture = "default" },
    ["inv_aritim"] = { index_key = 2041771272, subculture = "sc_rom_etruscan", culture = "default" },
    ["inv_balari"] = { index_key = 2041771397, subculture = "sc_rom_nuragic", culture = "default" },
    ["inv_bituriges"] = { index_key = 2041771223, subculture = "sc_rom_gaul", culture = "default" },
    ["inv_boii"] = { index_key = 2041771258, subculture = "sc_rom_gaul", culture = "default" },
    ["inv_bruttii"] = { index_key = 2041771364, subculture = "sc_rom_italic", culture = "default" },
    ["inv_carni"] = { index_key = 2041771237, subculture = "sc_rom_gaul", culture = "default" },
    ["inv_carnutes"] = { index_key = 2041771247, subculture = "sc_rom_gaul", culture = "default" },
    ["inv_carthage"] = { index_key = 2041771405, subculture = "sc_rom_carthaginian", culture = "default" },
    ["inv_cenomani"] = { index_key = 2041771256, subculture = "sc_rom_gaul", culture = "default" },
    ["inv_corsi"] = { index_key = 2041771401, subculture = "sc_rom_nuragic", culture = "default" },
    ["inv_croton"] = { index_key = 2041771372, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["inv_daunians"] = { index_key = 2041771326, subculture = "sc_rom_iapygian", culture = "default" },
    ["inv_felathri"] = { index_key = 2041771270, subculture = "sc_rom_etruscan", culture = "default" },
    ["inv_frentani"] = { index_key = 2041771314, subculture = "sc_rom_italic", culture = "default" },
    ["inv_hernici"] = { index_key = 2041771300, subculture = "sc_rom_italic", culture = "default" },
    ["inv_inc_helvetii"] = { index_key = 2041771641, subculture = "sc_rom_gaul", culture = "default" },
    ["inv_inc_hirpini"] = { index_key = 2041771655, subculture = "sc_rom_italic", culture = "default" },
    ["inv_inc_histri"] = { index_key = 2041771646, subculture = "sc_rom_gaul", culture = "default" },
    ["inv_inc_massylii"] = { index_key = 2041771669, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["inv_inc_nurrensi"] = { index_key = 2041771662, subculture = "sc_rom_nuragic", culture = "default" },
    ["inv_inc_sikelians"] = { index_key = 2041771668, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["inv_insubres"] = { index_key = 2041771224, subculture = "sc_rom_gaul", culture = "default" },
    ["inv_insubres_civil_war"] = { index_key = 2041771604, subculture = "sc_rom_gaul", culture = "default" },
    ["inv_insubres_secession"] = { index_key = 2041771606, subculture = "sc_rom_gaul", culture = "default" },
    ["inv_iolei"] = { index_key = 2041771206, subculture = "sc_rom_nuragic", culture = "default" },
    ["inv_iolei_civil_war"] = { index_key = 2041771407, subculture = "sc_rom_nuragic", culture = "default" },
    ["inv_iolei_secession"] = { index_key = 2041771416, subculture = "sc_rom_nuragic", culture = "default" },
    ["inv_lepontii"] = { index_key = 2041771214, subculture = "sc_rom_gaul", culture = "default" },
    ["inv_ligures"] = { index_key = 2041771244, subculture = "sc_rom_gaul", culture = "default" },
    ["inv_lucani"] = { index_key = 2041771343, subculture = "sc_rom_italic", culture = "default" },
    ["inv_marrucini"] = { index_key = 2041771297, subculture = "sc_rom_italic", culture = "default" },
    ["inv_messapians"] = { index_key = 2041771361, subculture = "sc_rom_iapygian", culture = "default" },
    ["inv_neapolis"] = { index_key = 2041771333, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["inv_paeligni"] = { index_key = 2041771321, subculture = "sc_rom_italic", culture = "default" },
    ["inv_peucetians"] = { index_key = 2041771351, subculture = "sc_rom_iapygian", culture = "default" },
    ["inv_picentes"] = { index_key = 2041771281, subculture = "sc_rom_italic", culture = "default" },
    ["inv_pirate_illyrian"] = { index_key = 2041771623, subculture = "sc_rom_illyrian", culture = "default" },
    ["inv_raeti"] = { index_key = 2041771227, subculture = "sc_rom_etruscan", culture = "default" },
    ["inv_rebel_carthage"] = { index_key = 2041771600, subculture = "sc_rom_carthaginian", culture = "default" },
    ["inv_rebel_etruscan"] = { index_key = 2041771581, subculture = "sc_rom_etruscan", culture = "default" },
    ["inv_rebel_gaul"] = { index_key = 2041771552, subculture = "sc_rom_gaul", culture = "default" },
    ["inv_rebel_greek"] = { index_key = 2041771567, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["inv_rebel_iapygian"] = { index_key = 2041771577, subculture = "sc_rom_iapygian", culture = "default" },
    ["inv_rebel_italic"] = { index_key = 2041771558, subculture = "sc_rom_italic", culture = "default" },
    ["inv_rebel_nuragic"] = { index_key = 2041771573, subculture = "sc_rom_nuragic", culture = "default" },
    ["inv_rebels_greek"] = { index_key = 2041771633, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["inv_rhegion"] = { index_key = 2041771591, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["inv_rome"] = { index_key = 2041771172, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["inv_rome_civil_war"] = { index_key = 2041771417, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["inv_rome_secession"] = { index_key = 2041771427, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["inv_sabines"] = { index_key = 2041771291, subculture = "sc_rom_italic", culture = "default" },
    ["inv_samnites"] = { index_key = 2041771182, subculture = "sc_rom_italic", culture = "default" },
    ["inv_samnites_civil_war"] = { index_key = 2041771433, subculture = "sc_rom_italic", culture = "default" },
    ["inv_samnites_secession"] = { index_key = 2041771440, subculture = "sc_rom_italic", culture = "default" },
    ["inv_senones"] = { index_key = 2041771181, subculture = "sc_rom_gaul", culture = "default" },
    ["inv_senones_civil_war"] = { index_key = 2041771448, subculture = "sc_rom_gaul", culture = "default" },
    ["inv_senones_secession"] = { index_key = 2041771454, subculture = "sc_rom_gaul", culture = "default" },
    ["inv_slaves_greek"] = { index_key = 2041771614, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["inv_syracuse"] = { index_key = 2041771194, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["inv_syracuse_civil_war"] = { index_key = 2041771461, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["inv_syracuse_secession"] = { index_key = 2041771465, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["inv_taranto"] = { index_key = 2041771187, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["inv_taranto_civil_war"] = { index_key = 2041771472, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["inv_taranto_secession"] = { index_key = 2041771477, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["inv_tarchuna"] = { index_key = 2041771177, subculture = "sc_rom_etruscan", culture = "default" },
    ["inv_tarchuna_civil_war"] = { index_key = 2041771487, subculture = "sc_rom_etruscan", culture = "default" },
    ["inv_tarchuna_secession"] = { index_key = 2041771497, subculture = "sc_rom_etruscan", culture = "default" },
    ["inv_umbri"] = { index_key = 2041771273, subculture = "sc_rom_italic", culture = "default" },
    ["inv_veii"] = { index_key = 2041771288, subculture = "sc_rom_etruscan", culture = "default" },
    ["inv_veneti"] = { index_key = 2041771197, subculture = "sc_rom_italic", culture = "default" },
    ["inv_veneti_civil_war"] = { index_key = 2041771502, subculture = "sc_rom_italic", culture = "default" },
    ["inv_veneti_secession"] = { index_key = 2041771511, subculture = "sc_rom_italic", culture = "default" },
    ["inv_viesul"] = { index_key = 2041771266, subculture = "sc_rom_etruscan", culture = "default" },
    ["inv_volsci"] = { index_key = 2041771310, subculture = "sc_rom_italic", culture = "default" },
    ["pel_aitolian"] = { index_key = 2041770251, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_akaian"] = { index_key = 2041770258, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_argos"] = { index_key = 2041770271, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_athenai"] = { index_key = 2041770197, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_athenai_civil_war"] = { index_key = 2041770203, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_athenai_secession"] = { index_key = 2041770768, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_boiotia"] = { index_key = 2041770224, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_boiotia_civil_war"] = { index_key = 2041770226, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_boiotia_secession"] = { index_key = 2041770771, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_byzantion"] = { index_key = 2041770295, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_elis"] = { index_key = 2041770266, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_epeiros"] = { index_key = 2041770242, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_gortyn"] = { index_key = 2041770282, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_ionian"] = { index_key = 2041770287, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_knossos"] = { index_key = 2041770284, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_korinthos"] = { index_key = 2041770232, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_korinthos_civil_war"] = { index_key = 2041770237, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_korinthos_secession"] = { index_key = 2041770772, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_korkyra"] = { index_key = 2041770243, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_kydonia"] = { index_key = 2041770280, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_makedon"] = { index_key = 2041770238, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_melos"] = { index_key = 2041770277, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_persia"] = { index_key = 2041770304, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["pel_rebels_aiolian"] = { index_key = 2041770336, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_rebels_akaian"] = { index_key = 2041770328, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_rebels_barbarian"] = { index_key = 2041770353, subculture = "sc_rom_daco_thracian", culture = "default" },
    ["pel_rebels_dorian"] = { index_key = 2041770319, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_rebels_ionian"] = { index_key = 2041770310, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_rebels_makedonian"] = { index_key = 2041770349, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_rebels_other_greeks"] = { index_key = 2041770340, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_rebels_persian"] = { index_key = 2041770355, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["pel_rodos"] = { index_key = 2041770286, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_sparta"] = { index_key = 2041770211, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_sparta_civil_war"] = { index_key = 2041770220, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_sparta_secession"] = { index_key = 2041770778, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_thessaly"] = { index_key = 2041770250, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pel_thraike"] = { index_key = 2041770299, subculture = "sc_rom_daco_thracian", culture = "default" },
    ["pro_gaul"] = { index_key = 2041768810, subculture = "sc_rom_celtic", culture = "default" },
    ["pro_greek_cities"] = { index_key = 2041768813, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pro_lucanian"] = { index_key = 2041768817, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["pro_rebels"] = { index_key = 2041768946, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["pro_roman_allies"] = { index_key = 2041768954, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["pro_rome"] = { index_key = 2041768803, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["pro_samnites"] = { index_key = 2041768806, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["pun_allobroges"] = { index_key = 2041769488, subculture = "sc_rom_gaul", culture = "default" },
    ["pun_arevaci"] = { index_key = 2041769585, subculture = "sc_rom_celtiberian", culture = "default" },
    ["pun_arevaci_civil_war"] = { index_key = 2041769596, subculture = "sc_rom_celtiberian", culture = "default" },
    ["pun_arevaci_secession"] = { index_key = 2041770779, subculture = "sc_rom_celtiberian", culture = "default" },
    ["pun_astures"] = { index_key = 2041769514, subculture = "sc_rom_celtiberian", culture = "default" },
    ["pun_boii"] = { index_key = 2041769460, subculture = "sc_rom_gaul", culture = "default" },
    ["pun_cantrabri"] = { index_key = 2041769512, subculture = "sc_rom_celtiberian", culture = "default" },
    ["pun_carpetani"] = { index_key = 2041769434, subculture = "sc_rom_celtiberian", culture = "default" },
    ["pun_carthage"] = { index_key = 2041769407, subculture = "sc_rom_carthaginian", culture = "default" },
    ["pun_carthage_civil_war"] = { index_key = 2041769594, subculture = "sc_rom_carthaginian", culture = "default" },
    ["pun_carthage_secession"] = { index_key = 2041770783, subculture = "sc_rom_carthaginian", culture = "default" },
    ["pun_celtici"] = { index_key = 2041769440, subculture = "sc_rom_celtiberian", culture = "default" },
    ["pun_cessetani"] = { index_key = 2041769497, subculture = "sc_rom_celtiberian", culture = "default" },
    ["pun_emporion"] = { index_key = 2041769396, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pun_etruscan"] = { index_key = 2041769370, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["pun_gaetuli"] = { index_key = 2041769538, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["pun_galleaci"] = { index_key = 2041769523, subculture = "sc_rom_celtiberian", culture = "default" },
    ["pun_garamantia"] = { index_key = 2041769539, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["pun_illercavones"] = { index_key = 2041769426, subculture = "sc_rom_celtiberian", culture = "default" },
    ["pun_illergetes"] = { index_key = 2041769504, subculture = "sc_rom_celtiberian", culture = "default" },
    ["pun_insubres"] = { index_key = 2041769474, subculture = "sc_rom_celtic", culture = "default" },
    ["pun_libya"] = { index_key = 2041769591, subculture = "sc_rom_carthaginian", culture = "default" },
    ["pun_liguria"] = { index_key = 2041769485, subculture = "sc_rom_celtic", culture = "default" },
    ["pun_lusitani"] = { index_key = 2041769580, subculture = "sc_rom_celtiberian", culture = "default" },
    ["pun_lusitani_civil_war"] = { index_key = 2041769602, subculture = "sc_rom_celtiberian", culture = "default" },
    ["pun_lusitani_secession"] = { index_key = 2041770784, subculture = "sc_rom_celtiberian", culture = "default" },
    ["pun_masaesyli"] = { index_key = 2041769405, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["pun_massilia"] = { index_key = 2041769386, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pun_massyli"] = { index_key = 2041769429, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["pun_mauri"] = { index_key = 2041769529, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["pun_oretani"] = { index_key = 2041769421, subculture = "sc_rom_celtiberian", culture = "default" },
    ["pun_rebel_african"] = { index_key = 2041769556, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["pun_rebel_celt"] = { index_key = 2041769557, subculture = "sc_rom_celtic", culture = "default" },
    ["pun_rebel_celtiberian"] = { index_key = 2041769552, subculture = "sc_rom_celtiberian", culture = "default" },
    ["pun_rebel_hellenic"] = { index_key = 2041769559, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pun_rebel_latin"] = { index_key = 2041769563, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["pun_rebel_punic"] = { index_key = 2041769570, subculture = "sc_rom_carthaginian", culture = "default" },
    ["pun_rome"] = { index_key = 2041769373, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["pun_rome_civil_war"] = { index_key = 2041769593, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["pun_rome_secession"] = { index_key = 2041770788, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["pun_samnites"] = { index_key = 2041769379, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["pun_syracuse"] = { index_key = 2041769382, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pun_syracuse_civil_war"] = { index_key = 2041769614, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pun_syracuse_secession"] = { index_key = 2041770789, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["pun_tarbelli"] = { index_key = 2041769490, subculture = "sc_rom_celtiberian", culture = "default" },
    ["pun_turdetani"] = { index_key = 2041769417, subculture = "sc_rom_celtiberian", culture = "default" },
    ["pun_vaccaei"] = { index_key = 2041769445, subculture = "sc_rom_celtiberian", culture = "default" },
    ["pun_vascones"] = { index_key = 2041769493, subculture = "sc_rom_celtiberian", culture = "default" },
    ["pun_veneti"] = { index_key = 2041769468, subculture = "sc_rom_celtic", culture = "default" },
    ["pun_vettones"] = { index_key = 2041769454, subculture = "sc_rom_celtiberian", culture = "default" },
    ["pun_volcae"] = { index_key = 2041769477, subculture = "sc_rom_gaul", culture = "default" },
    ["rom_aedui"] = { index_key = 2041768317, subculture = "sc_rom_gaul", culture = "default" },
    ["rom_aestii"] = { index_key = 2041768528, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["rom_anartes"] = { index_key = 2041768517, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_aorsoi"] = { index_key = 2041768613, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["rom_arachosia"] = { index_key = 2041768667, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["rom_ardhan"] = { index_key = 2041768609, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["rom_ardiaei"] = { index_key = 2041768466, subculture = "sc_rom_illyrian", culture = "default" },
    ["rom_ardiaei_civil_war"] = { index_key = 2041769630, subculture = "sc_rom_illyrian", culture = "default" },
    ["rom_ardiaei_secession"] = { index_key = 2041770797, subculture = "sc_rom_illyrian", culture = "default" },
    ["rom_arevaci"] = { index_key = 2041768260, subculture = "sc_rom_celtiberian", culture = "default" },
    ["rom_arevaci_civil_war"] = { index_key = 2041769597, subculture = "sc_rom_celtiberian", culture = "default" },
    ["rom_arevaci_secession"] = { index_key = 2041770804, subculture = "sc_rom_celtiberian", culture = "default" },
    ["rom_aria"] = { index_key = 2041768660, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["rom_armenia"] = { index_key = 2041768576, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["rom_armenia_civil_war"] = { index_key = 2041769648, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["rom_armenia_secession"] = { index_key = 2041770808, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["rom_artebartes"] = { index_key = 2041768343, subculture = "sc_rom_gaul", culture = "default" },
    ["rom_arverni"] = { index_key = 2041768299, subculture = "sc_rom_gaul", culture = "default" },
    ["rom_arverni_civil_war"] = { index_key = 2041768969, subculture = "sc_rom_gaul", culture = "default" },
    -- Table of all Total War: Rome II factions with their index keys, subcultures, and mapped cultures (continued)

    ["rom_arverni_secession"] = { index_key = 2041770816, subculture = "sc_rom_gaul", culture = "default" },
    ["rom_athens"] = { index_key = 2041768474, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_athens_civil_war"] = { index_key = 2041769002, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_athens_secession"] = { index_key = 2041770820, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_axum"] = { index_key = 2041768744, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["rom_baktria"] = { index_key = 2041768643, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_baktria_civil_war"] = { index_key = 2041769037, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_baktria_secession"] = { index_key = 2041770823, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_bastarnae"] = { index_key = 2041768513, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_biephi"] = { index_key = 2041768509, subculture = "sc_rom_daco_thracian", culture = "default" },
    ["rom_bithynia"] = { index_key = 2041768551, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["rom_blemmyes"] = { index_key = 2041768736, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["rom_boii"] = { index_key = 2041768403, subculture = "sc_rom_gaul", culture = "default" },
    ["rom_boii_civil_war"] = { index_key = 2041769363, subculture = "sc_rom_gaul", culture = "default" },
    ["rom_boii_secession"] = { index_key = 2041770829, subculture = "sc_rom_gaul", culture = "default" },
    ["rom_breuci"] = { index_key = 2041768446, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_brigantes"] = { index_key = 2041768216, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["rom_budini"] = { index_key = 2041768520, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["rom_caledones"] = { index_key = 2041768214, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["rom_cantabri"] = { index_key = 2041768253, subculture = "sc_rom_celtiberian", culture = "default" },
    ["rom_cappadocia"] = { index_key = 2041768567, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["rom_carnutes"] = { index_key = 2041768315, subculture = "sc_rom_gaul", culture = "default" },
    ["rom_carthage"] = { index_key = 2041768177, subculture = "sc_rom_carthaginian", culture = "default" },
    ["rom_carthage_civil_war"] = { index_key = 2041768951, subculture = "sc_rom_carthaginian", culture = "default" },
    ["rom_carthage_secession"] = { index_key = 2041770830, subculture = "sc_rom_carthaginian", culture = "default" },
    ["rom_catiaroi"] = { index_key = 2041768530, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["rom_celtici"] = { index_key = 2041768236, subculture = "sc_rom_celtiberian", culture = "default" },
    ["rom_cessetani"] = { index_key = 2041768275, subculture = "sc_rom_celtiberian", culture = "default" },
    ["rom_cherusci"] = { index_key = 2041768359, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["rom_cimbri"] = { index_key = 2041768423, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["rom_cimmeria"] = { index_key = 2041768542, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_cimmeria_civil_war"] = { index_key = 2041770194, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_cimmeria_secession"] = { index_key = 2041770840, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_colchis"] = { index_key = 2041768598, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_colchis_civil_war"] = { index_key = 2041770195, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_colchis_secession"] = { index_key = 2041770849, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_cyprus"] = { index_key = 2041768568, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_cyrenaica"] = { index_key = 2041768746, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_dahae"] = { index_key = 2041768639, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["rom_daorsi"] = { index_key = 2041768461, subculture = "sc_rom_illyrian", culture = "default" },
    ["rom_delmatae"] = { index_key = 2041768455, subculture = "sc_rom_illyrian", culture = "default" },
    ["rom_demetae"] = { index_key = 2041768225, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["rom_drangiana"] = { index_key = 2041768673, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["rom_dumnonii"] = { index_key = 2041768229, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["rom_ebdani"] = { index_key = 2041768211, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["rom_edetani"] = { index_key = 2041768270, subculture = "sc_rom_celtiberian", culture = "default" },
    ["rom_epirus"] = { index_key = 2041768472, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_epirus_civil_war"] = { index_key = 2041769003, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_epirus_secession"] = { index_key = 2041770856, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_eravisci"] = { index_key = 2041768437, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_etruscan"] = { index_key = 2041768202, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["rom_frisii"] = { index_key = 2041768356, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["rom_gaetuli"] = { index_key = 2041768775, subculture = "sc_rom_numidian", culture = "rom_eastern" },
    ["rom_galatia"] = { index_key = 2041768557, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_galatia_civil_war"] = { index_key = 2041769360, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_galatia_secession"] = { index_key = 2041770866, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_galleaci"] = { index_key = 2041768247, subculture = "sc_rom_celtiberian", culture = "default" },
    ["rom_garamantia"] = { index_key = 2041768757, subculture = "sc_rom_numidian", culture = "rom_eastern" },
    ["rom_gerrhaea"] = { index_key = 2041768696, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["rom_getae"] = { index_key = 2041768506, subculture = "sc_rom_daco_thracian", culture = "default" },
    ["rom_getae_civil_war"] = { index_key = 2041769636, subculture = "sc_rom_daco_thracian", culture = "default" },
    ["rom_getae_secession"] = { index_key = 2041770867, subculture = "sc_rom_daco_thracian", culture = "default" },
    ["rom_gutones"] = { index_key = 2041768426, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["rom_helvetii"] = { index_key = 2041768328, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_himyar"] = { index_key = 2041768714, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["rom_iceni"] = { index_key = 2041768204, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["rom_iceni_civil_war"] = { index_key = 2041768965, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["rom_iceni_secession"] = { index_key = 2041770871, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["rom_insubres"] = { index_key = 2041768376, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_kartli"] = { index_key = 2041768602, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["rom_khorasmii"] = { index_key = 2041768633, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["rom_knossos"] = { index_key = 2041768543, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_kush"] = { index_key = 2041771146, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["rom_kush_civil_war"] = { index_key = 2041771155, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["rom_kush_secession"] = { index_key = 2041771151, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["rom_libya"] = { index_key = 2041768761, subculture = "sc_rom_carthaginian", culture = "default" },
    ["rom_liguria"] = { index_key = 2041768383, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_lugii"] = { index_key = 2041768427, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["rom_lusitani"] = { index_key = 2041768240, subculture = "sc_rom_celtiberian", culture = "default" },
    ["rom_lusitani_civil_war"] = { index_key = 2041769612, subculture = "sc_rom_celtiberian", culture = "default" },
    ["rom_lusitani_secession"] = { index_key = 2041770878, subculture = "sc_rom_celtiberian", culture = "default" },
    ["rom_ma_in"] = { index_key = 2041768723, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["rom_macedon"] = { index_key = 2041768178, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_macedon_civil_war"] = { index_key = 2041768970, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_macedon_secession"] = { index_key = 2041770881, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_marcomanni"] = { index_key = 2041768369, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["rom_masaesyli"] = { index_key = 2041768767, subculture = "sc_rom_numidian", culture = "rom_eastern" },
    ["rom_masaesyli_civil_war"] = { index_key = 2041771127, subculture = "sc_rom_numidian", culture = "rom_eastern" },
    ["rom_masaesyli_secession"] = { index_key = 2041771132, subculture = "sc_rom_numidian", culture = "rom_eastern" },
    ["rom_mascat"] = { index_key = 2041768702, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["rom_massagetae"] = { index_key = 2041768632, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["rom_massagetae_civil_war"] = { index_key = 2041769023, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["rom_massagetae_secession"] = { index_key = 2041770883, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["rom_massilia"] = { index_key = 2041768326, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_massilia_civil_war"] = { index_key = 2041770204, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_massilia_secession"] = { index_key = 2041770890, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_media"] = { index_key = 2041768570, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["rom_media_atropatene"] = { index_key = 2041768585, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["rom_meroe"] = { index_key = 2041768739, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["rom_nabatea"] = { index_key = 2041768732, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["rom_nabatea_civil_war"] = { index_key = 2041771159, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["rom_nabatea_secession"] = { index_key = 2041771165, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["rom_namnetes"] = { index_key = 2041768309, subculture = "sc_rom_gaul", culture = "default" },
    ["rom_nasamones"] = { index_key = 2041768751, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["rom_nervii"] = { index_key = 2041768346, subculture = "sc_rom_gaul", culture = "default" },
    ["rom_nervii_civil_war"] = { index_key = 2041769358, subculture = "sc_rom_gaul", culture = "default" },
    ["rom_nervii_secession"] = { index_key = 2041770897, subculture = "sc_rom_gaul", culture = "default" },
    ["rom_nori"] = { index_key = 2041768395, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_nova_carthago"] = { index_key = 2041768230, subculture = "sc_rom_carthaginian", culture = "default" },
    ["rom_odryssia"] = { index_key = 2041768499, subculture = "sc_rom_daco_thracian", culture = "default" },
    ["rom_odryssia_civil_war"] = { index_key = 2041769638, subculture = "sc_rom_daco_thracian", culture = "default" },
    ["rom_odryssia_secession"] = { index_key = 2041770900, subculture = "sc_rom_daco_thracian", culture = "default" },
    ["rom_parthava"] = { index_key = 2041768695, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["rom_parthia"] = { index_key = 2041768650, subculture = "sc_rom_parthian", culture = "rom_eastern" },
    ["rom_parthia_civil_war"] = { index_key = 2041768954, subculture = "sc_rom_parthian", culture = "rom_eastern" },
    ["rom_parthia_secession"] = { index_key = 2041770905, subculture = "sc_rom_parthian", culture = "rom_eastern" },
    ["rom_pergamon"] = { index_key = 2041768549, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_pergamon_civil_war"] = { index_key = 2041770211, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_pergamon_secession"] = { index_key = 2041770915, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_persia"] = { index_key = 2041768688, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["rom_pictones"] = { index_key = 2041768303, subculture = "sc_rom_gaul", culture = "default" },
    ["rom_pontus"] = { index_key = 2041768552, subculture = "sc_rom_pontic", culture = "rom_eastern" },
    ["rom_pontus_civil_war"] = { index_key = 2041768960, subculture = "sc_rom_pontic", culture = "rom_eastern" },
    ["rom_pontus_secession"] = { index_key = 2041770925, subculture = "sc_rom_pontic", culture = "rom_eastern" },
    ["rom_ptolemaics"] = { index_key = 2041768188, subculture = "sc_rom_egyptian", culture = "default" },
    ["rom_ptolemaics_civil_war"] = { index_key = 2041768978, subculture = "sc_rom_egyptian", culture = "default" },
    ["rom_ptolemaics_secession"] = { index_key = 2041770930, subculture = "sc_rom_egyptian", culture = "default" },
    ["rom_qidri"] = { index_key = 2041768694, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["rom_raeti"] = { index_key = 2041768374, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_rebel_african"] = { index_key = 2041768902, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["rom_rebel_arabian"] = { index_key = 2041768874, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["rom_rebel_briton"] = { index_key = 2041768917, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["rom_rebel_celt"] = { index_key = 2041768853, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_rebel_dacian"] = { index_key = 2041768933, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_rebel_eastern"] = { index_key = 2041768883, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["rom_rebel_egyptian"] = { index_key = 2041768942, subculture = "sc_rom_egyptian", culture = "default" },
    ["rom_rebel_german"] = { index_key = 2041768861, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["rom_rebel_hellenic"] = { index_key = 2041768878, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_rebel_iberian"] = { index_key = 2041768907, subculture = "sc_rom_celtiberian", culture = "default" },
    ["rom_rebel_illyrian"] = { index_key = 2041768922, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_rebel_latin"] = { index_key = 2041768864, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["rom_rebel_nomadic"] = { index_key = 2041768889, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["rom_rebel_punic"] = { index_key = 2041768872, subculture = "sc_rom_carthaginian", culture = "default" },
    ["rom_rebel_spartan"] = { index_key = 2041768938, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_rebel_thracian"] = { index_key = 2041768928, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_rhodos"] = { index_key = 2041768833, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_rome"] = { index_key = 2041768170, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["rom_rome_civil_war"] = { index_key = 2041768843, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["rom_rome_secession"] = { index_key = 2041770935, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["rom_roxolani"] = { index_key = 2041768622, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["rom_roxolani_civil_war"] = { index_key = 2041769020, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["rom_roxolani_secession"] = { index_key = 2041770941, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["rom_rugii"] = { index_key = 2041768417, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["rom_saba"] = { index_key = 2041768705, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["rom_saba_civil_war"] = { index_key = 2041771140, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["rom_saba_secession"] = { index_key = 2041771134, subculture = "sc_rom_african_arabian", culture = "rom_eastern" },
    ["rom_sagartia"] = { index_key = 2041768682, subculture = "sc_rom_eastern", culture = "rom_eastern" },
    ["rom_sardes"] = { index_key = 2041768559, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_scordisci"] = { index_key = 2041768490, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_scythia"] = { index_key = 2041768540, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["rom_scythia_civil_war"] = { index_key = 2041769010, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["rom_scythia_secession"] = { index_key = 2041770949, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["rom_seleucid"] = { index_key = 2041768199, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_seleucid_civil_war"] = { index_key = 2041769031, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_seleucid_secession"] = { index_key = 2041770953, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_sequani"] = { index_key = 2041768336, subculture = "sc_rom_gaul", culture = "default" },
    ["rom_siraces"] = { index_key = 2041768610, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["rom_slave"] = { index_key = 2041768826, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["rom_sparta"] = { index_key = 2041768189, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_sparta_civil_war"] = { index_key = 2041768992, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_sparta_secession"] = { index_key = 2041770961, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_suebi"] = { index_key = 2041768408, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["rom_suebi_civil_war"] = { index_key = 2041768982, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["rom_suebi_secession"] = { index_key = 2041770965, subculture = "sc_rom_germanic", culture = "rom_barbarian" },
    ["rom_syracuse"] = { index_key = 2041768781, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_syracuse_civil_war"] = { index_key = 2041769622, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_syracuse_secession"] = { index_key = 2041770971, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_thyssagetae"] = { index_key = 2041768631, subculture = "sc_rom_barb_east", culture = "rom_barbarian" },
    ["rom_trapezos"] = { index_key = 2041768590, subculture = "sc_rom_greek", culture = "rom_hellenistic" },
    ["rom_treverii"] = { index_key = 2041768339, subculture = "sc_rom_gaul", culture = "default" },
    ["rom_triballi"] = { index_key = 2041768485, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_turdetani"] = { index_key = 2041768233, subculture = "sc_rom_celtiberian", culture = "default" },
    ["rom_tylis"] = { index_key = 2041768484, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_tylis_civil_war"] = { index_key = 2041769646, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_tylis_secession"] = { index_key = 2041770979, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_veneti"] = { index_key = 2041768393, subculture = "sc_rom_celtic", culture = "default" },
    ["rom_vivisci"] = { index_key = 2041768283, subculture = "sc_rom_gaul", culture = "default" },
    ["rom_volcae"] = { index_key = 2041768291, subculture = "sc_rom_gaul", culture = "default" },
    ["test_easterners"] = { index_key = 2041768793, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["test_islanders"] = { index_key = 2041768800, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["test_northerners"] = { index_key = 2041768782, subculture = "sc_rom_roman", culture = "rom_roman" },
    ["test_southerners"] = { index_key = 2041768797, subculture = "sc_rom_british", culture = "rom_barbarian" },
    ["test_westerners"] = { index_key = 2041768783, subculture = "sc_rom_british", culture = "rom_barbarian" }
}

-- Function to get the culture of a faction based on its name
function getFactionCulture(factionName)
    local faction = factions[factionName]
    if faction then
        return faction.culture
    else
        return "default"
    end
end

function get_faction_name()
    -- Access the EpisodicScripting module
    local scripting = package.loaded['lua_scripts.EpisodicScripting']
    if not scripting or not scripting.game_interface then
        return "default_nil"
    end

    local game = scripting.game_interface
    local world = game:model():world()
    if not world then
        return "default_nil"
    end

    -- Try to get a selected character first (assuming selection via CampaignUI or context)
    -- Since CampaignUI does not provide a direct "get selected character" method,
    -- we rely on character_list and prioritize human factions
    local faction_list = world:faction_list()
    if not faction_list or faction_list:is_empty() then
        return "default_nil"
    end

    -- Iterate through factions to find a human faction first
    for i = 0, faction_list:num_items() - 1 do
        local faction = faction_list:item_at(i)
        if faction and faction:is_human() then
            local character_list = faction:character_list()
            if character_list and not character_list:is_empty() then
                local char = character_list:item_at(0)
                if char and not char:is_null_interface() then
                    local faction = char:faction()
                    if faction and not faction:is_null_interface() then
                        local faction_name = faction:name()
                        if faction_name and type(faction_name) == "string" and faction_name ~= "" then
                            return faction_name
                        end
                    end
                end
            end
        end
    end

    -- If no human faction character is found, try any faction's first character
    for i = 0, faction_list:num_items() - 1 do
        local faction = faction_list:item_at(i)
        if faction and not faction:is_null_interface() then
            local character_list = faction:character_list()
            if character_list and not character_list:is_empty() then
                local char = character_list:item_at(0)
                if char and not char:is_null_interface() then
                    local faction = char:faction()
                    if faction and not faction:is_null_interface() then
                        local faction_name = faction:name()
                        if faction_name and type(faction_name) == "string" and faction_name ~= "" then
                            return faction_name
                        end
                    end
                end
            end
        end
    end

    -- Return default if no faction name is found
    return "default_nil"
end


return ai_battle_data

