
-- Defines culture-specific battle preferences

local DEBUG = GLOBAL_DEBUG

require("battle_ai_planner_data/ai_battle_data")

ai_cultures_battle_data = {
    rom_Roman = {
        strategy_weights = { overrun = 0.9, advance = 1.2, stand_and_fight = 1.2, defend = 1.0, retreat = 0.9 },
        tactic_weights = {
            melee_attack = 1.1,
            pikewall_attack = 1.1,
            gettodefendingpositions = 1.0,
            flanking_infantry = 0.8,
            flanking_cavalry = 0.65,
            siege_attacking_extra_waves = 0.9,
            secure_flanks = 1.1,
            wave_attacks = 1.35,
            missile_attacking = 0.8,
            fallback = 0.515,
            fallout_siege = 0.75,
            rotate_units = 1.65,
            extra_siege_defending_ai = 1.25,
            roman_testudo = 1.25,
            missile_cavalry_skirmish = 1.1,
            elephant_rampage = 0.8,
        },
        preferred_formations = {
            overrun = "formation_flanking",
            advance = "formation_stable",
            stand_and_fight = "formation_stable",
            defend = "formation_stable",
            retreat = "normal_formation",
            melee_attack = "formation_infantry_wedge",
            pikewall_attack = "double_formation",
            gettodefendingpositions = "formation_stable",
            flanking_infantry = "formation_flanking",
            flanking_cavalry = "formation_cavalrycharge",
            siege_attacking_extra_waves = "normal_formation",
            secure_flanks = "formation_flanking",
            wave_attacks = "formation_stable",
            missile_attacking = "formation_stable",
            fallback = nil,
            fallout_siege = "formation_cavalrycharge",
            rotate_units = "formation_stable",
            extra_siege_defending_ai = "formation_stable",
            roman_testudo = "roman_testudo",
        },
        tactic_ids = {
            generic_001 = true,
            generic_002 = true,
            generic_003 = true,
            generic_004 = true,
            generic_005 = true,
            generic_006 = true,
            generic_007 = true,
            generic_008 = true,
            generic_009 = true,
            generic_010 = true,
            generic_011 = true,
            generic_012 = true,
            generic_013 = true,
            generic_014 = true,
            generic_015 = true,
            generic_016 = true,
            generic_017 = true,
            generic_018 = true,
            generic_019 = true,
            generic_020 = true,
            generic_021 = true,
            generic_022 = true,
            generic_023 = true,
            generic_024 = true,
            generic_027 = true,
            roman_001 = true,
        },
    },

    rom_Eastern = {
        strategy_weights = { overrun = 1.0, advance = 1.1, stand_and_fight = 1.0, defend = 0.65, retreat = 1.0 },
        tactic_weights = {
            melee_attack = 0.9,
            pikewall_attack = 0.9,
            gettodefendingpositions = 0.8,
            flanking_infantry = 0.725,
            flanking_cavalry = 1.25,
            siege_attacking_extra_waves = 0.8,
            secure_flanks = 0.95,
            wave_attacks = 0.95,
            missile_attacking = 1.5,
            fallback = 1.1,
            fallout_siege = 1.0,
            rotate_units = 0.8,
            extra_siege_defending_ai = 0.98,
            parthian_circle = 1.55,
            eastern_opening_harass = 1.85,
            missile_cavalry_skirmish = 1.55,
            elephant_rampage = 1.2,
        },
        preferred_formations = {
            overrun = "normal_formation",
            advance = "normal_formation",
            stand_and_fight = "normal_formation",
            defend = "formation_stable",
            retreat = "normal_formation",
            melee_attack = "formation_cavalrycharge",
            pikewall_attack = "double_formation",
            gettodefendingpositions = "normal_formation",
            flanking_infantry = "normal_formation",
            flanking_cavalry = "formation_cavalrycharge",
            siege_attacking_extra_waves = "normal_formation",
            secure_flanks = "normal_formation",
            wave_attacks = "normal_formation",
            missile_attacking = "normal_formation",
            fallback = nil,
            fallout_siege = "formation_cavalrycharge",
            rotate_units = "normal_formation",
            extra_siege_defending_ai = "normal_formation",
            parthian_circle = "normal_formation",
        },
        tactic_ids = {
            generic_001 = true,
            generic_002 = true,
            generic_003 = true,
            generic_004 = true,
            generic_005 = true,
            generic_006 = true,
            generic_007 = true,
            generic_008 = true,
            generic_009 = true,
            generic_010 = true,
            generic_011 = true,
            generic_012 = true,
            generic_013 = true,
            generic_014 = true,
            generic_015 = true,
            generic_016 = true,
            generic_017 = true,
            generic_018 = true,
            generic_019 = true,
            generic_020 = true,
            generic_021 = true,
            generic_022 = true,
            generic_023 = true,
            generic_027 = true,
            parthian_001 = true,
            eastern_002 = true,
        },
    },

    rom_Barbarian = {
        strategy_weights = { overrun = 1.3, advance = 1.3, stand_and_fight = 1.0, defend = 0.8, retreat = 0.76 },
        tactic_weights = {
            melee_attack = 1.3,
            pikewall_attack = 0.5,
            gettodefendingpositions = 0.7,
            flanking_infantry = 1.1,
            flanking_cavalry = 1.0,
            siege_attacking_extra_waves = 0.9,
            secure_flanks = 0.8,
            wave_attacks = 1.2,
            missile_attacking = 0.9,
            fallback = 0.6,
            fallout_siege = 1.55,
            rotate_units = 0.76,
            extra_siege_defending_ai = 0.7,
            missile_cavalry_skirmish = 0.9,
            elephant_rampage = 1.15,
            forest_ambush = 1.5,
        },
        preferred_formations = {
            overrun = "formation_flanking",
            advance = "normal_formation",
            stand_and_fight = "normal_formation",
            defend = "normal_formation",
            retreat = "normal_formation",
            melee_attack = "formation_infantry_wedge",
            pikewall_attack = "double_formation",
            gettodefendingpositions = "normal_formation",
            flanking_infantry = "formation_flanking",
            flanking_cavalry = "formation_cavalrycharge",
            siege_attacking_extra_waves = "normal_formation",
            secure_flanks = "formation_flanking",
            wave_attacks = "normal_formation",
            missile_attacking = "normal_formation",
            fallback = nil,
            fallout_siege = "formation_cavalrycharge",
            rotate_units = "normal_formation",
            extra_siege_defending_ai = "normal_formation",
        },
        tactic_ids = {
            generic_001 = true,
            generic_002 = true,
            generic_003 = true,
            generic_004 = true,
            generic_005 = true,
            generic_006 = true,
            generic_007 = true,
            generic_008 = true,
            generic_009 = true,
            generic_010 = true,
            generic_011 = true,
            generic_012 = true,
            generic_013 = true,
            generic_014 = true,
            generic_015 = true,
            generic_016 = true,
            generic_017 = true,
            generic_018 = true,
            generic_019 = true,
            generic_020 = true,
            generic_021 = true,
            generic_022 = true,
            generic_023 = true,
            generic_024 = true,
            generic_027 = true,
            barbarian_001 = true,
        },
    },

    rom_Hellenistic = {
        strategy_weights = { overrun = 1.0, advance = 1.0, stand_and_fight = 1.1, defend = 1.0, retreat = 0.9 },
        tactic_weights = {
            melee_attack = 1.0,
            pikewall_attack = 1.28,
            gettodefendingpositions = 1.0,
            flanking_infantry = 0.9,
            flanking_cavalry = 1.1,
            siege_attacking_extra_waves = 0.9,
            secure_flanks = 1.0,
            wave_attacks = 1.0,
            missile_attacking = 1.0,
            elephant_rampage = 1.1,
            fallback = 0.5,
            fallout_siege = 0.9,
            rotate_units = 1.0,
            missile_cavalry_skirmish = 1.0,
            extra_siege_defending_ai = 1.0,
        },
        preferred_formations = {
            overrun = "normal_formation",
            advance = "normal_formation",
            stand_and_fight = "formation_stable",
            defend = "formation_stable",
            retreat = "normal_formation",
            melee_attack = "double_formation",
            pikewall_attack = "double_formation",
            gettodefendingpositions = "formation_stable",
            flanking_infantry = "formation_flanking",
            flanking_cavalry = "formation_cavalrycharge",
            siege_attacking_extra_waves = "normal_formation",
            secure_flanks = "formation_flanking",
            wave_attacks = "formation_stable",
            missile_attacking = "normal_formation",
            fallback = nil,
            fallout_siege = "formation_cavalrycharge",
            rotate_units = "formation_stable",
            extra_siege_defending_ai = "formation_stable",
        },
        tactic_ids = {
            generic_001 = true,
            generic_002 = true,
            generic_003 = true,
            generic_004 = true,
            generic_005 = true,
            generic_006 = true,
            generic_007 = true,
            generic_008 = true,
            generic_009 = true,
            generic_010 = true,
            generic_011 = true,
            generic_012 = true,
            generic_013 = true,
            generic_014 = true,
            generic_015 = true,
            generic_016 = true,
            generic_017 = true,
            generic_018 = true,
            generic_019 = true,
            generic_020 = true,
            generic_021 = true,
            generic_022 = true,
            generic_023 = true,
            generic_024 = true,
            generic_027 = true,
        },
    },

    default = {
        strategy_weights = { overrun = 1.0, advance = 1.0, stand_and_fight = 1.0, defend = 1.0, retreat = 1.0 },
        tactic_weights = {
            melee_attack = 1.2,
            pikewall_attack = 1.0,
            gettodefendingpositions = 1.0,
            flanking_infantry = 1.05,
            flanking_cavalry = 1.08,
            siege_attacking_extra_waves = 1.0,
            secure_flanks = 1.0,
            wave_attacks = 1.0,
            missile_attacking = 1.0,
            fallback = 0.5,
            fallout_siege = 1.0,
            rotate_units = 1.0,
            missile_cavalry_skirmish = 1.0,
            extra_siege_defending_ai = 1.0,
            elephant_rampage = 1.0,
        },
        preferred_formations = {
            overrun = "normal_formation",
            advance = "normal_formation",
            stand_and_fight = "normal_formation",
            defend = "normal_formation",
            retreat = "normal_formation",
            melee_attack = "normal_formation",
            pikewall_attack = "double_formation",
            gettodefendingpositions = "normal_formation",
            flanking_infantry = "normal_formation",
            flanking_cavalry = "formation_cavalrycharge",
            siege_attacking_extra_waves = "normal_formation",
            secure_flanks = "normal_formation",
            wave_attacks = "normal_formation",
            missile_attacking = "normal_formation",
            fallback = nil,
            fallout_siege = "formation_cavalrycharge",
            rotate_units = "normal_formation",
            extra_siege_defending_ai = "normal_formation",
        },
        tactic_ids = {
            generic_001 = true,
            generic_002 = true,
            generic_003 = true,
            generic_004 = true,
            generic_005 = true,
            generic_006 = true,
            generic_007 = true,
            generic_008 = true,
            generic_009 = true,
            generic_010 = true,
            generic_011 = true,
            generic_012 = true,
            generic_013 = true,
            generic_014 = true,
            generic_015 = true,
            generic_016 = true,
            generic_017 = true,
            generic_018 = true,
            generic_019 = true,
            generic_020 = true,
            generic_021 = true,
            generic_022 = true,
            generic_023 = true,
            generic_024 = true,
            generic_027 = true,
        },
    },
}

return ai_cultures_battle_data

-- EOF
